### ISSUE TITLE
【内部解析报错】使用mqttx链接无法连上

### ISSUE THREAD

**Issue by JeasonLaung** [hyperf/mqtt-server-incubator#3]
使用mqttx链接无法连上

```cmd
[WARNING] Simps\MQTT\Exception\LengthException: unpack remaining length error, get 1297(0) in /www/wwwroot/abc.com/hyperf/vendor/simps/mqtt/src/Tools/UnPackTool.php:30
Stack trace:
#0 /www/wwwroot/abc.com/hyperf/vendor/simps/mqtt/src/Packet/UnPack.php(32): Simps\MQTT\Tools\UnPackTool::string()
#1 /www/wwwroot/abc.com/hyperf/vendor/simps/mqtt/src/Protocol/V3.php(86): Simps\MQTT\Packet\UnPack::connect()
#2 /www/wwwroot/abc.com/hyperf/vendor/hyperf/mqtt-server-incubator/src/MQTTServer.php(174): Simps\MQTT\Protocol\V3::unpack()
#3 /www/wwwroot/abc.com/hyperf/vendor/hyperf/mqtt-server-incubator/src/MQTTServer.php(113): Hyperf\MqttServer\MQTTServer->buildRequest()
#4 {main}
```

**Comment by JeasonLaung** [comment]
版本不正确导致，关闭issue
